### ISSUE TITLE
Google Drive Uploader: "invalid credentials" all of a sudden

### ISSUE THREAD

**Issue by JayBrown** [soulseekah/bash-utils#1]
The Google Drive uploader worked fine, but now, after ca. 1 hour the output says:

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "authError",
    "message": "Invalid Credentials",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Invalid Credentials"
 }
}

I was just using some test file, a couple of KB, nothing fancy. Is there a way to correct this? Of course I understand that your script is not the problem. But maybe you know a way out.

PS: maybe it's because I also have a second Google account which is interfering somehow? It's always online via GMail IMAP. (?)

**Comment by soulseekah** [comment]
Make sure your API keys are for https://developers.google.com/identity/protocols/OAuth2WebServer#offline offline access, this should make sure your keys don't expire so fast.

**Comment by JayBrown** [comment]
I have setup a new application ("other", not "web application"), but I've not seen a setting to allow offline access, neither on the device page when getting the tokens nor in my Google account settings nor in the Drive API settings nor in the uploader application settings. So how do you go about it? Do I have to add some code to one of your scripts to activate offline access?

**Comment by soulseekah** [comment]
There is no "offline access" button, you need to select the appropriate application type to get that, I don't remember which one it is, try some of the others. Closing this issue as irrelevant to the code.

**Comment by menny** [comment]
@soulseekah can you add this (and maybe other) information to the README file?

**Comment by soulseekah** [comment]
@menny perhaps, what do you think should be added?

**Comment by menny** [comment]
- How to obtain the token (with link to the console)
- How to correctly setup the token.
- An example for a run (like you have in other [README](https://github.com/soulseekah/bash-utils/blob/master/log-monitor-events/README))

Thanks!

**Comment by soulseekah** [comment]
@menny sounds good, feel free to put one together and send in a pull request.
